# Archivo: render.yaml
services:
  - type: web
    name: nfc-app-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        value: postgres://avnadmin:AVNS_Ovm2E51S8aWVTpvyf-i@pg-1471beb2-nfc-tag.g.aivencloud.com:17937/defaultdb?sslmode=require
      - key: JWT_SECRET_KEY
        value: super_secret_nfc_app_key_2025_final_fix_xyz

  - type: web
    name: nfc-app-frontend
    env: static
    plan: free
    staticPublishPath: ./frontend/dist
    buildCommand: npm install && npm run build
    envVars:
      - key: VITE_API_URL
        value: /api
